# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010103)
$foreground = rgb(88B8F8)
$color0 = rgb(010103)
$color1 = rgb(881B1E)
$color2 = rgb(1D508D)
$color3 = rgb(1A6B8C)
$color4 = rgb(168184)
$color5 = rgb(9D271F)
$color6 = rgb(175CA9)
$color7 = rgb(72A3E0)
$color8 = rgb(3C6EA8)
$color9 = rgb(881B1E)
$color10 = rgb(1D508D)
$color11 = rgb(1A6B8C)
$color12 = rgb(168184)
$color13 = rgb(9D271F)
$color14 = rgb(175CA9)
$color15 = rgb(B0C8E7)
