general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 15
    on-timeout = brightnessctl -s set 1%
    on-resume = brightnessctl -r
}

listener {
    timeout = 17
    on-timeout = hyprlock
}
