[Audio]
Volume=100

[General]
ColorScheme=Breeze Dark
FileDialogLastLocation=file:///home/kvnx/Shows/From.S03.1080p.x265-ELiTE
LastPlayedFile=file:///home/kvnx/Projects/JSc/Udemy - The Complete JavaScript Course 2025 From Zero to Expert! (2025-10)/18 - Forkify App Building a Modern Application %5BPROJECT%5D/027 Wrapping Up Final Considerations.mp4

[Playback]
OpenLastPlayedFile=true
PauseWhileMinimized=true
RestoreFilePosition=true

[Playlist]
OpenWithSingleClick=true
RememberState=true
