[Audio]
Volume=100

[General]
ColorScheme=Breeze Dark
FileDialogLastLocation=file:///home/kvnx/Shows/From.S03.1080p.x265-ELiTE
GuiStyle=Windows
LastPlayedFile=file:///home/kvnx/Shows/1_YT/Clayton Bigsby, the World’s Only Black White Supremacist - Chappelle’s Show %5BBLNDqxrUUwQ%5D.webm

[Playback]
OpenLastPlayedFile=true
PauseWhileMinimized=true
RestoreFilePosition=true
YtdlFormat=bestvideo[height<=720]+bestaudio/best

[Playlist]
OpenWithSingleClick=true
RememberState=true
