#!/hint/bash
# shellcheck disable=2034

#
# /etc/makepkg.conf.d/fortran.conf
#

#########################################################################
# FORTRAN LANGUAGE SUPPORT
#########################################################################

# Flags used for the Fortran compiler, optimized for local hardware
FFLAGS="-O3 -march=native -pipe -fno-plt"
FCFLAGS="$FFLAGS"

# Additional compiler flags appended to `FFLAGS` and `FCFLAGS` for use in debugging.
DEBUG_FFLAGS="-g"
