#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 <URL>"
    exit 1
fi

URL="$1"

# -f: Priorities 720p MP4, falls back to best available under 720p if needed
yt-dlp \
    --yes-playlist \
    --ignore-config \
    -f "bv[height<=720][ext=mp4]+ba[ext=m4a]/b[height<=720][ext=mp4] / bv[height<=720]+ba/b[height<=720]" \
    --merge-output-format mp4 \
    --embed-metadata \
    --embed-thumbnail \
    -o "%(playlist_title)s/%(playlist_index)s - %(title)s.%(ext)s" \
    "$URL"
