# ~/.config/foot/foot.ini
[main]
font=monospace:size=13
pad=15x15
selection-target=both

[key-bindings]
# Unbound so Ctrl+C cancels commands
clipboard-copy=Control+c
clipboard-paste=Control+v

[cursor]
style=underline
blink=yes
underline-thickness=5
blink-rate=400 

[colors-dark]
alpha=0.7
background=010103
foreground=88B8F8

# Selection Highlight Colors (Pink)
selection-background=168184
selection-foreground=010103

cursor=010103 168184

## Normal colors
regular0=010103
regular1=881B1E
regular2=1D508D
regular3=1A6B8C
regular4=168184
regular5=9D271F
regular6=175CA9
regular7=72A3E0

## Bright colors
bright0=3C6EA8
bright1=881B1E
bright2=1D508D
bright3=1A6B8C
bright4=168184
bright5=9D271F
bright6=175CA9
bright7=B0C8E7
